services:
  foxloop2:
    image: ghcr.io/m4rpqfbbc2-debug/foxloop2-workflows:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foxloop2-workflows
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOX_PROCESS or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - ./cache:/usr/src/app/cache
    networks:
      - foxloop2
  postgres:
    image: 'postgres:14.4'
    container_name: foxloop2-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foxloop2
  redis:
    image: 'redis:7.0.7'
    container_name: foxloop2-redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks:
      - foxloop2
volumes:
  postgres_data:
  redis_data:
networks:
  foxloop2:
